[2024-06-17T16:54:35.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T16:54:35.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_dbt_execute.run_dbt manual__2024-06-17T16:54:25.270424+00:00 [queued]>
[2024-06-17T16:54:35.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_dbt_execute.run_dbt manual__2024-06-17T16:54:25.270424+00:00 [queued]>
[2024-06-17T16:54:35.238+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-17T16:54:35.248+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_dbt> on 2024-06-17 16:54:25.270424+00:00
[2024-06-17T16:54:35.265+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-17T16:54:35.271+0000] {standard_task_runner.py:63} INFO - Started process 87 to run task
[2024-06-17T16:54:35.268+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'full_dbt_execute', 'run_dbt', 'manual__2024-06-17T16:54:25.270424+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/full_dbt_execute.py', '--cfg-path', '/tmp/tmpry7q_l65']
[2024-06-17T16:54:35.278+0000] {standard_task_runner.py:91} INFO - Job 210: Subtask run_dbt
[2024-06-17T16:54:35.370+0000] {task_command.py:426} INFO - Running <TaskInstance: full_dbt_execute.run_dbt manual__2024-06-17T16:54:25.270424+00:00 [running]> on host 4c2406045e40
[2024-06-17T16:54:35.458+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_dbt_execute' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T16:54:25.270424+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T16:54:25.270424+00:00'
[2024-06-17T16:54:35.462+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T16:54:35.553+0000] {docker.py:366} INFO - Starting docker container from image custom_dbt_image
[2024-06-17T16:54:35.592+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-17T16:54:37.794+0000] {docker.py:436} INFO - [0m16:54:37  Running with dbt=1.5.0
[2024-06-17T16:54:37.975+0000] {docker.py:436} INFO - [0m16:54:37  Unable to do partial parsing because of a version mismatch
[2024-06-17T16:54:38.972+0000] {docker.py:436} INFO - [0m16:54:38  Found 3 models, 4 tests, 0 snapshots, 0 analyses, 341 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics, 0 groups
[2024-06-17T16:54:38.976+0000] {docker.py:436} INFO - [0m16:54:38
[2024-06-17T16:54:44.503+0000] {docker.py:436} INFO - [0m16:54:44  Concurrency: 1 threads (target='dev')
[2024-06-17T16:54:44.512+0000] {docker.py:436} INFO - [0m16:54:44
[2024-06-17T16:54:44.514+0000] {docker.py:436} INFO - [0m16:54:44  1 of 2 START sql table model mint.my_first_dbt_model ........................... [RUN]
[2024-06-17T16:54:44.855+0000] {docker.py:436} INFO - [0m16:54:44  1 of 2 OK created sql table model mint.my_first_dbt_model ...................... [[32mOK[0m in 0.34s]
[2024-06-17T16:54:44.867+0000] {docker.py:436} INFO - [0m16:54:44  2 of 2 START sql view model mint.my_second_dbt_model ........................... [RUN]
[2024-06-17T16:54:45.178+0000] {docker.py:436} INFO - [0m16:54:45  2 of 2 OK created sql view model mint.my_second_dbt_model ...................... [[32mOK[0m in 0.31s]
[2024-06-17T16:54:45.244+0000] {docker.py:436} INFO - [0m16:54:45
[2024-06-17T16:54:45.246+0000] {docker.py:436} INFO - [0m16:54:45  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 6.27 seconds (6.27s).
[2024-06-17T16:54:45.266+0000] {docker.py:436} INFO - [0m16:54:45
[2024-06-17T16:54:45.269+0000] {docker.py:436} INFO - [0m16:54:45  [32mCompleted successfully[0m
[2024-06-17T16:54:45.271+0000] {docker.py:436} INFO - [0m16:54:45
[2024-06-17T16:54:45.278+0000] {docker.py:436} INFO - [0m16:54:45  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2024-06-17T16:54:47.462+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T16:54:47.520+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=full_dbt_execute, task_id=run_dbt, run_id=manual__2024-06-17T16:54:25.270424+00:00, execution_date=20240617T165425, start_date=20240617T165435, end_date=20240617T165447
[2024-06-17T16:54:47.576+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-17T16:54:47.628+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-17T16:54:47.629+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
