[2024-06-17T16:33:24.857+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T16:33:24.874+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_dbt_execute.run_dbt manual__2024-06-17T16:33:19.936822+00:00 [queued]>
[2024-06-17T16:33:24.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_dbt_execute.run_dbt manual__2024-06-17T16:33:19.936822+00:00 [queued]>
[2024-06-17T16:33:24.878+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-17T16:33:24.884+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_dbt> on 2024-06-17 16:33:19.936822+00:00
[2024-06-17T16:33:24.894+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-17T16:33:24.895+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2024-06-17T16:33:24.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'full_dbt_execute', 'run_dbt', 'manual__2024-06-17T16:33:19.936822+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/full_dbt_execute.py', '--cfg-path', '/tmp/tmpp7cazlk7']
[2024-06-17T16:33:24.897+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask run_dbt
[2024-06-17T16:33:24.947+0000] {task_command.py:426} INFO - Running <TaskInstance: full_dbt_execute.run_dbt manual__2024-06-17T16:33:19.936822+00:00 [running]> on host 204b6a35fe73
[2024-06-17T16:33:25.049+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_dbt_execute' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T16:33:19.936822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T16:33:19.936822+00:00'
[2024-06-17T16:33:25.053+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T16:33:25.180+0000] {docker.py:366} INFO - Starting docker container from image custom_dbt_image
[2024-06-17T16:33:25.213+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-17T16:33:27.488+0000] {docker.py:436} INFO - [0m16:33:27  Running with dbt=1.5.0
[2024-06-17T16:33:27.584+0000] {docker.py:436} INFO - [0m16:33:27  Unable to do partial parsing because of a version mismatch
[2024-06-17T16:33:28.182+0000] {docker.py:436} INFO - [0m16:33:28  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 341 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2024-06-17T16:33:28.184+0000] {docker.py:436} INFO - [0m16:33:28
[2024-06-17T16:33:30.463+0000] {docker.py:436} INFO - [0m16:33:30  Concurrency: 1 threads (target='dev')
[2024-06-17T16:33:30.477+0000] {docker.py:436} INFO - [0m16:33:30
[2024-06-17T16:33:30.481+0000] {docker.py:436} INFO - [0m16:33:30  1 of 2 START sql table model mint.my_first_dbt_model ........................... [RUN]
[2024-06-17T16:33:30.768+0000] {docker.py:436} INFO - [0m16:33:30  1 of 2 OK created sql table model mint.my_first_dbt_model ...................... [[32mOK[0m in 0.29s]
[2024-06-17T16:33:30.771+0000] {docker.py:436} INFO - [0m16:33:30  2 of 2 START sql view model mint.my_second_dbt_model ........................... [RUN]
[2024-06-17T16:33:30.895+0000] {docker.py:436} INFO - [0m16:33:30  2 of 2 OK created sql view model mint.my_second_dbt_model ...................... [[32mOK[0m in 0.12s]
[2024-06-17T16:33:30.989+0000] {docker.py:436} INFO - [0m16:33:30
[2024-06-17T16:33:30.990+0000] {docker.py:436} INFO - [0m16:33:30  Finished running 1 table model, 1 view model in 0 hours 0 minutes and 2.80 seconds (2.80s).
[2024-06-17T16:33:31.003+0000] {docker.py:436} INFO - [0m16:33:31
[2024-06-17T16:33:31.006+0000] {docker.py:436} INFO - [0m16:33:31  [32mCompleted successfully[0m
[2024-06-17T16:33:31.009+0000] {docker.py:436} INFO - [0m16:33:31
[2024-06-17T16:33:31.011+0000] {docker.py:436} INFO - [0m16:33:31  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2024-06-17T16:33:33.114+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T16:33:33.415+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=full_dbt_execute, task_id=run_dbt, run_id=manual__2024-06-17T16:33:19.936822+00:00, execution_date=20240617T163319, start_date=20240617T163324, end_date=20240617T163333
[2024-06-17T16:33:33.566+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-17T16:33:33.793+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-17T16:33:33.798+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
